version: '3.8'
services:
  registry-service:
    container_name: ms-registry-service
    restart: always
    build: ./registry-service/
    ports:
      - "8761:8761"
    networks:
      - mynet
  vault-service:
    image: vault:latest
    container_name: ms-vault-service
    restart: always
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "mysecrettoken"
    ports:
      - "8200:8200"
    networks:
      - mynet
  mysql:
    image: mysql
    restart: always
    volumes:
      - rvdor_users-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: rvdor_users
    networks:
      - mynet
  config-server:
    container_name: ms-config-server
    restart: always
    build: ./config-server/
    ports:
      - "8888:8888"
    networks:
      - mynet
    depends_on:
      - registry-service
  user-service:
    container_name: ms-user-service
    restart: always
    build: ./user-service/
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      - config-server
      - registry-service
      - mysql
#  ticket-service:
#    container_name: ms-ticket-service
#    restart: always
#    build: ./ticket-service/
#    ports:
#      - "8090:8090"
#    networks:
#      - mynet
#    depends_on:
#      - config-server
#      - registry-service
#      - mysql
#      - user-service
#  payments-service:
#    container_name: ms-payments-service
#    restart: always
#    build: ./payments-service/
#    ports:
#      - "8070:8070"
#    networks:
#      - mynet
#    depends_on:
#      - config-server
#      - registry-service
#      - mysql
#  api-gateway:
#    container_name: ms-api-gateway
#    restart: always
#    build: ./api-gateway/
#    ports:
#      - "9191:9191"
#    networks:
#      - mynet
#    depends_on:
#      - registry-service
networks:
  mynet:
    external: true
volumes:
  rvdor_users-data: