server:
  port: '8070'
spring:
  kafka:
    producer:
      bootstrap-servers: kafka1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: PAYMENTS-SERVICE
  datasource:
    url: 'jdbc:mysql://mysql/rvdor_payments'
    username: root
    password: '123456'
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      dialect: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate:
      ddl-auto: 'update'
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://registry-service:8761/eureka
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always