server:
  port: '8080'
spring:
  datasource:
    url: 'jdbc:mysql://localhost/rvdor_users'
    username: root
    password: '12345678'
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      dialect: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate:
      ddl-auto: 'update'