server:
  port: '8888'
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: vault,git
  cloud:
    config:
      server:
        vault:
          scheme: http
          host: localhost
          port: 8200
          authentication: TOKEN
          token: hvs.nmTnKoOAItoYTLrNvKd0z8Mc
          kvVersion: 2
          order: 1
          profileSeparator: /
        git:
          uri: https://github.com/ricardovasquezpe/revendedor-config-server
          clone-on-start: true
          default-label: main
          order: 2
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/